apiVersion: v1
kind: Service
metadata:
  name: checkpoint1
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: checkpoint1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkpoint1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkpoint1
  template:
    metadata:
      labels:
        app: checkpoint1
    spec:
      containers:
        - name: checkpoint1
          image: checkpoint1:1.0
